### ISSUE TITLE
mac 重启后 ssh 已断开但 tab 颜色与 badge 依然残留

### ISSUE THREAD

**Issue by Martian746** [shawn-bluce/server_tag#3]
0. ssh 连上后，server_tag 如预期修改了 tab 颜色与 badge；
1. ssh 未断开。mac 重启，并还原了 iterm2 窗口；
2. ssh 已断开的 tab 依然残留有重启前的 tab 颜色与 badge。

**Comment by shawn-bluce** [comment]
@Martian746 理解了，后面空了来解决这个问题

**Comment by shawn-bluce** [comment]
新版本 macOS 和 iTerm2 无法复现了
